<?php

namespace Database\Seeders;

use App\Models\Booking;
use App\Models\Service;
use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class BarbershopSeeder extends Seeder
{
    public function run(): void
    {
        // ========================================================
        // 1. SEEDER USERS (21 Baris Data)
        // ========================================================
        $password = Hash::make('password');

        $users = [
            // Admin (1 akun)
            [
                'name' => 'Administrator',
                'email' => 'admin@gmail.com',
                'password' => $password,
                'phone' => '081234567890',
                'role' => 'admin',
                'created_at' => now(),
            ],
            // Customers (20 akun)
            [
                'name' => 'Dimas Pratama',
                'email' => 'dimas@gmail.com',
                'password' => $password,
                'phone' => '089876543210',
                'role' => 'customer',
                'created_at' => now()->subDays(20),
            ],
            [
                'name' => 'Rian Hidayat',
                'email' => 'rian@gmail.com',
                'password' => $password,
                'phone' => '081399887766',
                'role' => 'customer',
                'created_at' => now()->subDays(19),
            ],
            [
                'name' => 'Budi Santoso',
                'email' => 'budi@gmail.com',
                'password' => $password,
                'phone' => '085711223344',
                'role' => 'customer',
                'created_at' => now()->subDays(18),
            ],
            [
                'name' => 'Kevin Sanjaya',
                'email' => 'kevin@gmail.com',
                'password' => $password,
                'phone' => '082133445566',
                'role' => 'customer',
                'created_at' => now()->subDays(17),
            ],
            [
                'name' => 'Ahmad Fauzi',
                'email' => 'fauzi@gmail.com',
                'password' => $password,
                'phone' => '087799001122',
                'role' => 'customer',
                'created_at' => now()->subDays(16),
            ],
            [
                'name' => 'Doni Prasetyo',
                'email' => 'doni@gmail.com',
                'password' => $password,
                'phone' => '081299881122',
                'role' => 'customer',
                'created_at' => now()->subDays(15),
            ],
            [
                'name' => 'Eko Kurniawan',
                'email' => 'eko@gmail.com',
                'password' => $password,
                'phone' => '083812345678',
                'role' => 'customer',
                'created_at' => now()->subDays(14),
            ],
            [
                'name' => 'Rizky Pratama',
                'email' => 'rizky@gmail.com',
                'password' => $password,
                'phone' => '085678901234',
                'role' => 'customer',
                'created_at' => now()->subDays(13),
            ],
            [
                'name' => 'Fajar Nugraha',
                'email' => 'fajar@gmail.com',
                'password' => $password,
                'phone' => '081234098765',
                'role' => 'customer',
                'created_at' => now()->subDays(12),
            ],
            [
                'name' => 'Hendra Wijaya',
                'email' => 'hendra@gmail.com',
                'password' => $password,
                'phone' => '087811223344',
                'role' => 'customer',
                'created_at' => now()->subDays(11),
            ],
            [
                'name' => 'Ilham Saputra',
                'email' => 'ilham@gmail.com',
                'password' => $password,
                'phone' => '089912345678',
                'role' => 'customer',
                'created_at' => now()->subDays(10),
            ],
            [
                'name' => 'Joko Susanto',
                'email' => 'joko@gmail.com',
                'password' => $password,
                'phone' => '081277665544',
                'role' => 'customer',
                'created_at' => now()->subDays(9),
            ],
            [
                'name' => 'Bayu Setiawan',
                'email' => 'bayu@gmail.com',
                'password' => $password,
                'phone' => '085211224455',
                'role' => 'customer',
                'created_at' => now()->subDays(8),
            ],
            [
                'name' => 'Aditya Wardhana',
                'email' => 'aditya@gmail.com',
                'password' => $password,
                'phone' => '081344556677',
                'role' => 'customer',
                'created_at' => now()->subDays(7),
            ],
            [
                'name' => 'Gilang Ramadhan',
                'email' => 'gilang@gmail.com',
                'password' => $password,
                'phone' => '087788990011',
                'role' => 'customer',
                'created_at' => now()->subDays(6),
            ],
            [
                'name' => 'Tri Wahyudi',
                'email' => 'tri@gmail.com',
                'password' => $password,
                'phone' => '082233445566',
                'role' => 'customer',
                'created_at' => now()->subDays(5),
            ],
            [
                'name' => 'Wahyu Hidayat',
                'email' => 'wahyu@gmail.com',
                'password' => $password,
                'phone' => '085912345678',
                'role' => 'customer',
                'created_at' => now()->subDays(4),
            ],
            [
                'name' => 'Surya Darmawan',
                'email' => 'surya@gmail.com',
                'password' => $password,
                'phone' => '081987654321',
                'role' => 'customer',
                'created_at' => now()->subDays(3),
            ],
            [
                'name' => 'Dwi Cahyono',
                'email' => 'dwi@gmail.com',
                'password' => $password,
                'phone' => '081255667788',
                'role' => 'customer',
                'created_at' => now()->subDays(2),
            ],
            [
                'name' => 'Bagus Permana',
                'email' => 'bagus@gmail.com',
                'password' => $password,
                'phone' => '087899887766',
                'role' => 'customer',
                'created_at' => now()->subDays(1),
            ],
        ];

        foreach ($users as $userData) {
            User::firstOrCreate(['email' => $userData['email']], $userData);
        }

        // ========================================================
        // 2. SEEDER SERVICES (20 Baris Data Menu Layanan)
        // ========================================================
        $services = [
            [
                'nama_layanan' => 'Gentleman Haircut & Styling',
                'kategori' => 'Haircut',
                'harga' => 65000,
                'durasi' => 45,
                'deskripsi' => 'Potong rambut presisi bentuk wajah, cuci rambut bersih, pijat kepala ringan, dan pomade styling.',
                'is_active' => true,
            ],
            [
                'nama_layanan' => 'Classic Regular Haircut',
                'kategori' => 'Haircut',
                'harga' => 35000,
                'durasi' => 30,
                'deskripsi' => 'Potongan rambut standar rapi dan cepat untuk kebutuhan sehari-hari.',
                'is_active' => true,
            ],
            [
                'nama_layanan' => 'Undercut & Taper Fade Precision',
                'kategori' => 'Haircut',
                'harga' => 50000,
                'durasi' => 40,
                'deskripsi' => 'Gradasi fade halus (low/mid/high fade) dengan razor line tajam di sisi samping.',
                'is_active' => true,
            ],
            [
                'nama_layanan' => 'Buzz Cut & Clean Line Up',
                'kategori' => 'Haircut',
                'harga' => 30000,
                'durasi' => 20,
                'deskripsi' => 'Potongan botak militer rapi nomor 1-3 dengan garis tepi dahi dan cambang tegas.',
                'is_active' => true,
            ],
            [
                'nama_layanan' => 'Junior / Kids Haircut',
                'kategori' => 'Haircut',
                'harga' => 30000,
                'durasi' => 25,
                'deskripsi' => 'Cukur ramah anak usia 2-10 tahun dengan kapster sabar dan telaten.',
                'is_active' => true,
            ],
            [
                'nama_layanan' => 'French Crop & Textured Top',
                'kategori' => 'Haircut',
                'harga' => 55000,
                'durasi' => 40,
                'deskripsi' => 'Gaya rambut crop modern dengan poni tumpul dan tekstur natural di bagian atas.',
                'is_active' => true,
            ],
            [
                'nama_layanan' => 'Beard Trim & Hot Towel Shave',
                'kategori' => 'Shaving',
                'harga' => 45000,
                'durasi' => 30,
                'deskripsi' => 'Merapikan brewok dengan handuk hangat, krim cukur eksklusif, dan pisau cukur steril.',
                'is_active' => true,
            ],
            [
                'nama_layanan' => 'Mustache & Goatee Detailing',
                'kategori' => 'Shaving',
                'harga' => 30000,
                'durasi' => 20,
                'deskripsi' => 'Bentuk kumis dan jenggot presisi dengan trimmer mikro dan oil nutrisi.',
                'is_active' => true,
            ],
            [
                'nama_layanan' => 'Classic Head Shave (Gundul Licin)',
                'kategori' => 'Shaving',
                'harga' => 40000,
                'durasi' => 30,
                'deskripsi' => 'Cukur plontos licin menggunakan razor tajam, foam tebal, dan aftershave dingin.',
                'is_active' => true,
            ],
            [
                'nama_layanan' => 'Quick Beard Trimming',
                'kategori' => 'Shaving',
                'harga' => 25000,
                'durasi' => 15,
                'deskripsi' => 'Rapikan panjang brewok tanpa cukur licin untuk menjaga volume tetap proporsional.',
                'is_active' => true,
            ],
            [
                'nama_layanan' => 'Hair Wash & Tonic Massage',
                'kategori' => 'Treatment',
                'harga' => 30000,
                'durasi' => 20,
                'deskripsi' => 'Keramas air hangat 2x, kondisioner, hair tonic dingin, dan pijat relaksasi kepala.',
                'is_active' => true,
            ],
            [
                'nama_layanan' => 'Hair Creambath Ginseng Relaksasi',
                'kategori' => 'Treatment',
                'harga' => 75000,
                'durasi' => 45,
                'deskripsi' => 'Masker rambut herbal ginseng untuk memperkuat akar rambut ditambah pijat bahu leher.',
                'is_active' => true,
            ],
            [
                'nama_layanan' => 'Anti-Dandruff Scalp Treatment',
                'kategori' => 'Treatment',
                'harga' => 85000,
                'durasi' => 45,
                'deskripsi' => 'Pembersihan ketombe mendalam dengan serum tea tree oil dan steamer kulit kepala.',
                'is_active' => true,
            ],
            [
                'nama_layanan' => 'Black Charcoal Face Mask',
                'kategori' => 'Treatment',
                'harga' => 40000,
                'durasi' => 25,
                'deskripsi' => 'Masker arang komedo untuk membersihkan pori-pori dan mengangkat minyak wajah berlebih.',
                'is_active' => true,
            ],
            [
                'nama_layanan' => 'Basic Hair Color (Natural Black / Brown)',
                'kategori' => 'Coloring',
                'harga' => 95000,
                'durasi' => 60,
                'deskripsi' => 'Semir hitam atau cokelat gelap untuk menutup uban atau menyegarkan warna rambut alami.',
                'is_active' => true,
            ],
            [
                'nama_layanan' => 'Bleaching Level 8 + Ash Grey',
                'kategori' => 'Coloring',
                'harga' => 160000,
                'durasi' => 120,
                'deskripsi' => 'Proses bleaching aman bertahap dan pewarnaan abu-abu perak (ash grey trend).',
                'is_active' => true,
            ],
            [
                'nama_layanan' => 'Highlight & Streaks Coloring',
                'kategori' => 'Coloring',
                'harga' => 120000,
                'durasi' => 75,
                'deskripsi' => 'Aksen garis warna kontras pada helai rambut tertentu untuk dimensi gaya maksimal.',
                'is_active' => true,
            ],
            [
                'nama_layanan' => 'Combo Haircut + Beard Shave',
                'kategori' => 'Combo Package',
                'harga' => 80000,
                'durasi' => 60,
                'deskripsi' => 'Paket hemat potongan rambut komplit plus cukur rapi brewok handuk hangat.',
                'is_active' => true,
            ],
            [
                'nama_layanan' => 'Combo Haircut + Creambath Spa',
                'kategori' => 'Combo Package',
                'harga' => 110000,
                'durasi' => 75,
                'deskripsi' => 'Paket lengkap potong rambut, cuci bersih, creambath relaksasi, dan styling.',
                'is_active' => true,
            ],
            [
                'nama_layanan' => 'VIP Royal Full Grooming Package',
                'kategori' => 'Combo Package',
                'harga' => 150000,
                'durasi' => 90,
                'deskripsi' => 'Paket sultan: Haircut + Beard Shave + Scalp Treatment + Face Mask + Minuman Dingin.',
                'is_active' => true,
            ],
        ];

        foreach ($services as $svc) {
            Service::firstOrCreate(['nama_layanan' => $svc['nama_layanan']], $svc);
        }

        // ========================================================
        // 3. SEEDER BARBERS (5 Baris Data Kapster)
        // ========================================================
        $barbers = [
            ['name' => 'Rusdi', 'phone' => '081211112222', 'status' => 'available'],
            ['name' => 'Farhan', 'phone' => '081233334444', 'status' => 'available'],
            ['name' => 'Budi', 'phone' => '081255556666', 'status' => 'available'],
            ['name' => 'Agung', 'phone' => '081277778888', 'status' => 'break'],
            ['name' => 'Mas Gatot', 'phone' => '081299990000', 'status' => 'available'],
        ];

        foreach ($barbers as $brb) {
            DB::table('barbers')->updateOrInsert(
                ['name' => $brb['name']],
                [
                    'phone' => $brb['phone'],
                    'status' => $brb['status'],
                    'created_at' => now(),
                ]
            );
        }

        // ========================================================
        // 4. SEEDER BOOKINGS (25 Baris Data Reservasi)
        // ========================================================
        $sampleBookings = [
            [
                'booking_code' => 'BK-1001',
                'nama_pelanggan' => 'Dimas Pratama',
                'no_whatsapp' => '089876543210',
                'layanan' => 'Gentleman Haircut & Styling',
                'barber' => 'Rusdi (Master Barber)',
                'tanggal' => now()->format('Y-m-d'),
                'jam' => '10:00 WIB',
                'catatan' => 'Minta potong taper fade tipis samping.',
                'harga' => 65000,
                'status' => 'confirmed',
                'user_id' => 2,
            ],
            [
                'booking_code' => 'BK-1002',
                'nama_pelanggan' => 'Rian Hidayat',
                'no_whatsapp' => '081399887766',
                'layanan' => 'Beard Trim & Hot Towel Shave',
                'barber' => 'Budi (Classic Style)',
                'tanggal' => now()->format('Y-m-d'),
                'jam' => '10:45 WIB',
                'catatan' => 'Cukur rapi brewok.',
                'harga' => 45000,
                'status' => 'confirmed',
                'user_id' => 3,
            ],
            [
                'booking_code' => 'BK-1003',
                'nama_pelanggan' => 'Kevin Sanjaya',
                'no_whatsapp' => '082133445566',
                'layanan' => 'VIP Royal Full Grooming Package',
                'barber' => 'Farhan (Fade Specialist)',
                'tanggal' => now()->format('Y-m-d'),
                'jam' => '11:30 WIB',
                'catatan' => 'Persiapan acara wisuda siang ini.',
                'harga' => 150000,
                'status' => 'confirmed',
                'user_id' => 5,
            ],
            [
                'booking_code' => 'BK-1004',
                'nama_pelanggan' => 'Ahmad Fauzi',
                'no_whatsapp' => '087799001122',
                'layanan' => 'Classic Regular Haircut',
                'barber' => 'Agung (Beard & Shave)',
                'tanggal' => now()->format('Y-m-d'),
                'jam' => '13:00 WIB',
                'catatan' => 'Potong pendek rapi kerja kantor.',
                'harga' => 35000,
                'status' => 'pending',
                'user_id' => 6,
            ],
            [
                'booking_code' => 'BK-1005',
                'nama_pelanggan' => 'Budi Santoso',
                'no_whatsapp' => '085711223344',
                'layanan' => 'Combo Haircut + Beard Shave',
                'barber' => 'Rusdi (Master Barber)',
                'tanggal' => now()->format('Y-m-d'),
                'jam' => '13:45 WIB',
                'catatan' => 'Paket komplit cukur rambut dan kumis.',
                'harga' => 80000,
                'status' => 'confirmed',
                'user_id' => 4,
            ],
            [
                'booking_code' => 'BK-1006',
                'nama_pelanggan' => 'Doni Prasetyo',
                'no_whatsapp' => '081299881122',
                'layanan' => 'Hair Creambath Ginseng Relaksasi',
                'barber' => 'Farhan (Fade Specialist)',
                'tanggal' => now()->format('Y-m-d'),
                'jam' => '14:30 WIB',
                'catatan' => 'Pijatan kepala ekstra leher pegal.',
                'harga' => 75000,
                'status' => 'confirmed',
                'user_id' => 7,
            ],
            [
                'booking_code' => 'BK-1007',
                'nama_pelanggan' => 'Eko Kurniawan',
                'no_whatsapp' => '083812345678',
                'layanan' => 'Undercut & Taper Fade Precision',
                'barber' => 'Budi (Classic Style)',
                'tanggal' => now()->format('Y-m-d'),
                'jam' => '15:15 WIB',
                'catatan' => 'Model undercut slickback.',
                'harga' => 50000,
                'status' => 'pending',
                'user_id' => 8,
            ],
            [
                'booking_code' => 'BK-1008',
                'nama_pelanggan' => 'Rizky Pratama',
                'no_whatsapp' => '085678901234',
                'layanan' => 'Bleaching Level 8 + Ash Grey',
                'barber' => 'Rusdi (Master Barber)',
                'tanggal' => now()->format('Y-m-d'),
                'jam' => '16:00 WIB',
                'catatan' => 'Pewarnaan silver grey rambut atas.',
                'harga' => 160000,
                'status' => 'confirmed',
                'user_id' => 9,
            ],
            [
                'booking_code' => 'BK-1009',
                'nama_pelanggan' => 'Fajar Nugraha',
                'no_whatsapp' => '081234098765',
                'layanan' => 'French Crop & Textured Top',
                'barber' => 'Farhan (Fade Specialist)',
                'tanggal' => now()->format('Y-m-d'),
                'jam' => '17:00 WIB',
                'catatan' => 'Crop texture pendek ala Korea.',
                'harga' => 55000,
                'status' => 'confirmed',
                'user_id' => 10,
            ],
            [
                'booking_code' => 'BK-1010',
                'nama_pelanggan' => 'Hendra Wijaya',
                'no_whatsapp' => '087811223344',
                'layanan' => 'Anti-Dandruff Scalp Treatment',
                'barber' => 'Agung (Beard & Shave)',
                'tanggal' => now()->format('Y-m-d'),
                'jam' => '19:00 WIB',
                'catatan' => 'Treatment kulit kepala berketombe.',
                'harga' => 85000,
                'status' => 'confirmed',
                'user_id' => 11,
            ],
            [
                'booking_code' => 'BK-1011',
                'nama_pelanggan' => 'Ilham Saputra',
                'no_whatsapp' => '089912345678',
                'layanan' => 'Buzz Cut & Clean Line Up',
                'barber' => 'Budi (Classic Style)',
                'tanggal' => now()->format('Y-m-d'),
                'jam' => '19:45 WIB',
                'catatan' => 'Potong cepak militer no 2.',
                'harga' => 30000,
                'status' => 'pending',
                'user_id' => 12,
            ],
            [
                'booking_code' => 'BK-1012',
                'nama_pelanggan' => 'Joko Susanto',
                'no_whatsapp' => '081277665544',
                'layanan' => 'Junior / Kids Haircut',
                'barber' => 'Rusdi (Master Barber)',
                'tanggal' => now()->subDay()->format('Y-m-d'),
                'jam' => '10:00 WIB',
                'catatan' => 'Cukur anak umur 6 tahun.',
                'harga' => 30000,
                'status' => 'completed',
                'user_id' => 13,
            ],
            [
                'booking_code' => 'BK-1013',
                'nama_pelanggan' => 'Bayu Setiawan',
                'no_whatsapp' => '085211224455',
                'layanan' => 'Classic Head Shave (Gundul Licin)',
                'barber' => 'Agung (Beard & Shave)',
                'tanggal' => now()->subDay()->format('Y-m-d'),
                'jam' => '11:30 WIB',
                'catatan' => 'Gundul licin bersih razor.',
                'harga' => 40000,
                'status' => 'completed',
                'user_id' => 14,
            ],
            [
                'booking_code' => 'BK-1014',
                'nama_pelanggan' => 'Aditya Wardhana',
                'no_whatsapp' => '081344556677',
                'layanan' => 'Basic Hair Color (Natural Black / Brown)',
                'barber' => 'Farhan (Fade Specialist)',
                'tanggal' => now()->subDay()->format('Y-m-d'),
                'jam' => '13:00 WIB',
                'catatan' => 'Semir hitam natural tutup uban.',
                'harga' => 95000,
                'status' => 'completed',
                'user_id' => 15,
            ],
            [
                'booking_code' => 'BK-1015',
                'nama_pelanggan' => 'Gilang Ramadhan',
                'no_whatsapp' => '087788990011',
                'layanan' => 'Combo Haircut + Creambath Spa',
                'barber' => 'Rusdi (Master Barber)',
                'tanggal' => now()->subDay()->format('Y-m-d'),
                'jam' => '14:30 WIB',
                'catatan' => 'Potong rambut + spa kepala.',
                'harga' => 110000,
                'status' => 'completed',
                'user_id' => 16,
            ],
            [
                'booking_code' => 'BK-1016',
                'nama_pelanggan' => 'Tri Wahyudi',
                'no_whatsapp' => '082233445566',
                'layanan' => 'Black Charcoal Face Mask',
                'barber' => 'Budi (Classic Style)',
                'tanggal' => now()->subDay()->format('Y-m-d'),
                'jam' => '16:00 WIB',
                'catatan' => 'Masker arang komedo dan cuci muka.',
                'harga' => 40000,
                'status' => 'cancelled',
                'user_id' => 17,
            ],
            [
                'booking_code' => 'BK-1017',
                'nama_pelanggan' => 'Wahyu Hidayat',
                'no_whatsapp' => '085912345678',
                'layanan' => 'Highlight & Streaks Coloring',
                'barber' => 'Farhan (Fade Specialist)',
                'tanggal' => now()->subDays(2)->format('Y-m-d'),
                'jam' => '10:45 WIB',
                'catatan' => 'Highlight warna blonde pirang.',
                'harga' => 120000,
                'status' => 'completed',
                'user_id' => 18,
            ],
            [
                'booking_code' => 'BK-1018',
                'nama_pelanggan' => 'Surya Darmawan',
                'no_whatsapp' => '081987654321',
                'layanan' => 'Gentleman Haircut & Styling',
                'barber' => 'Rusdi (Master Barber)',
                'tanggal' => now()->subDays(2)->format('Y-m-d'),
                'jam' => '13:45 WIB',
                'catatan' => 'Side part pompadour rapi.',
                'harga' => 65000,
                'status' => 'completed',
                'user_id' => 19,
            ],
            [
                'booking_code' => 'BK-1019',
                'nama_pelanggan' => 'Dwi Cahyono',
                'no_whatsapp' => '081255667788',
                'layanan' => 'Mustache & Goatee Detailing',
                'barber' => 'Agung (Beard & Shave)',
                'tanggal' => now()->subDays(2)->format('Y-m-d'),
                'jam' => '15:15 WIB',
                'catatan' => 'Rapikan kumis melengkung.',
                'harga' => 30000,
                'status' => 'completed',
                'user_id' => 20,
            ],
            [
                'booking_code' => 'BK-1020',
                'nama_pelanggan' => 'Bagus Permana',
                'no_whatsapp' => '087899887766',
                'layanan' => 'VIP Royal Full Grooming Package',
                'barber' => 'Rusdi (Master Barber)',
                'tanggal' => now()->subDays(3)->format('Y-m-d'),
                'jam' => '11:30 WIB',
                'catatan' => 'Sesi lengkap menjelang lamaran nikah.',
                'harga' => 150000,
                'status' => 'completed',
                'user_id' => 21,
            ],
            [
                'booking_code' => 'BK-1021',
                'nama_pelanggan' => 'Dimas Pratama',
                'no_whatsapp' => '089876543210',
                'layanan' => 'Quick Beard Trimming',
                'barber' => 'Budi (Classic Style)',
                'tanggal' => now()->subDays(4)->format('Y-m-d'),
                'jam' => '14:00 WIB',
                'catatan' => 'Trimming cepat.',
                'harga' => 25000,
                'status' => 'completed',
                'user_id' => 2,
            ],
            [
                'booking_code' => 'BK-1022',
                'nama_pelanggan' => 'Rian Hidayat',
                'no_whatsapp' => '081399887766',
                'layanan' => 'Hair Wash & Tonic Massage',
                'barber' => 'Agung (Beard & Shave)',
                'tanggal' => now()->subDays(5)->format('Y-m-d'),
                'jam' => '17:00 WIB',
                'catatan' => 'Cuci rambut setelah olahraga.',
                'harga' => 30000,
                'status' => 'completed',
                'user_id' => 3,
            ],
            [
                'booking_code' => 'BK-1023',
                'nama_pelanggan' => 'Kevin Sanjaya',
                'no_whatsapp' => '082133445566',
                'layanan' => 'French Crop & Textured Top',
                'barber' => 'Farhan (Fade Specialist)',
                'tanggal' => now()->subDays(6)->format('Y-m-d'),
                'jam' => '19:00 WIB',
                'catatan' => 'Textured crop spike ringan.',
                'harga' => 55000,
                'status' => 'completed',
                'user_id' => 5,
            ],
            [
                'booking_code' => 'BK-1024',
                'nama_pelanggan' => 'Ahmad Fauzi',
                'no_whatsapp' => '087799001122',
                'layanan' => 'Gentleman Haircut & Styling',
                'barber' => 'Rusdi (Master Barber)',
                'tanggal' => now()->subDays(7)->format('Y-m-d'),
                'jam' => '10:00 WIB',
                'catatan' => 'Potong rutin bulanan.',
                'harga' => 65000,
                'status' => 'completed',
                'user_id' => 6,
            ],
            [
                'booking_code' => 'BK-1025',
                'nama_pelanggan' => 'Budi Santoso',
                'no_whatsapp' => '085711223344',
                'layanan' => 'Classic Regular Haircut',
                'barber' => 'Budi (Classic Style)',
                'tanggal' => now()->subDays(8)->format('Y-m-d'),
                'jam' => '13:00 WIB',
                'catatan' => 'Cukur rapi samping.',
                'harga' => 35000,
                'status' => 'completed',
                'user_id' => 4,
            ],
        ];

        foreach ($sampleBookings as $bk) {
            Booking::firstOrCreate(['booking_code' => $bk['booking_code']], $bk);
        }

        // ========================================================
        // 5. SEEDER REVIEWS (5 Baris Data Testimoni Pelanggan)
        // ========================================================
        $reviews = [
            [
                'user_id' => 2,
                'rating' => 5,
                'review' => 'Pelayanan luar biasa, tempat dingin dan bersih. Potongan taper fade Mas Rusdi presisi banget!',
                'created_at' => now()->subDays(3),
            ],
            [
                'user_id' => 3,
                'rating' => 5,
                'review' => 'Hot towel shave-nya juara, bikin rileks setelah pulang kantor. Produk pomade yang dipakai wangi.',
                'created_at' => now()->subDays(2),
            ],
            [
                'user_id' => 4,
                'rating' => 5,
                'review' => 'Kapster sangat ramah dan detail saat potong. Hasilnya sesuai referensi foto yang saya minta.',
                'created_at' => now()->subDays(1),
            ],
            [
                'user_id' => 5,
                'rating' => 5,
                'review' => 'Paket VIP Royal Grooming sangat worth it dengan harga segitu. Pijat kepalanya enak sekali!',
                'created_at' => now()->subHours(12),
            ],
            [
                'user_id' => 6,
                'rating' => 4,
                'review' => 'Barbershop terbaik di kota ini. Antrean rapi berkat fitur reservasi booking online web ini.',
                'created_at' => now()->subHours(6),
            ],
        ];

        foreach ($reviews as $rev) {
            DB::table('reviews')->updateOrInsert(
                ['user_id' => $rev['user_id']],
                $rev
            );
        }
    }
}
